apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: osf2f-ui
  name: osf2f-ui
  namespace: osf2f-system
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: osf2f-ui
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: osf2f-ui
    spec:
      containers:
        - image: ghcr.io/linuxsuren/goplay:osf2f-ui-dev
          imagePullPolicy: Always
          name: osf2f-ui
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: osf2f-controller-manager
      serviceAccountName: osf2f-controller-manager
      terminationGracePeriodSeconds: 30
