
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - osf2f.my.domain
  resources:
  - authors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - osf2f.my.domain
  resources:
  - authors/finalizers
  verbs:
  - update
- apiGroups:
  - osf2f.my.domain
  resources:
  - authors/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - osf2f.my.domain
  resources:
  - categories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - osf2f.my.domain
  resources:
  - categories/finalizers
  verbs:
  - update
- apiGroups:
  - osf2f.my.domain
  resources:
  - categories/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - osf2f.my.domain
  resources:
  - episodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - osf2f.my.domain
  resources:
  - episodes/finalizers
  verbs:
  - update
- apiGroups:
  - osf2f.my.domain
  resources:
  - episodes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - osf2f.my.domain
  resources:
  - notifiers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - osf2f.my.domain
  resources:
  - profiles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - osf2f.my.domain
  resources:
  - profiles/finalizers
  verbs:
  - update
- apiGroups:
  - osf2f.my.domain
  resources:
  - profiles/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - osf2f.my.domain
  resources:
  - rsses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - osf2f.my.domain
  resources:
  - rsses/finalizers
  verbs:
  - update
- apiGroups:
  - osf2f.my.domain
  resources:
  - rsses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - osf2f.my.domain
  resources:
  - showitems
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - osf2f.my.domain
  resources:
  - showitems/finalizers
  verbs:
  - update
- apiGroups:
  - osf2f.my.domain
  resources:
  - showitems/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - osf2f.my.domain
  resources:
  - shows
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - osf2f.my.domain
  resources:
  - shows/finalizers
  verbs:
  - update
- apiGroups:
  - osf2f.my.domain
  resources:
  - shows/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - osf2f.my.domain
  resources:
  - storages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - osf2f.my.domain
  resources:
  - storages/finalizers
  verbs:
  - update
- apiGroups:
  - osf2f.my.domain
  resources:
  - storages/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - osf2f.my.domain
  resources:
  - subscriptions
  verbs:
  - get
  - list
