# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/osf2f.my.domain_rsses.yaml
- bases/osf2f.my.domain_episodes.yaml
- bases/osf2f.my.domain_profiles.yaml
- bases/osf2f.my.domain_notifiers.yaml
- bases/osf2f.my.domain_categories.yaml
- bases/osf2f.my.domain_subscriptions.yaml
- bases/osf2f.my.domain_authors.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_rsses.yaml
#- patches/webhook_in_episodes.yaml
#- patches/webhook_in_profiles.yaml
#- patches/webhook_in_categories.yaml
#- patches/webhook_in_authors.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_rsses.yaml
#- patches/cainjection_in_episodes.yaml
#- patches/cainjection_in_profiles.yaml
#- patches/cainjection_in_categories.yaml
#- patches/cainjection_in_authors.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
